build-job:
   stage: build
   script: 
      - echo "Hello, $GITLAB_USER_NAME"

test: 
  image: cypress/base
  stage: test
  script:
    - npm ci
    - npm run cypress:run
  artifacts:
    when: always
    paths:
      - cypress/screenshots/*.png